SCREEN_WIDTH_TILES = 32
SCREEN_HEIGHT_TILES = 24

TILE_SIZE = 8

SCREEN_WIDTH = SCREEN_WIDTH_TILES * TILE_SIZE
SCREEN_HEIGHT = SCREEN_HEIGHT_TILES * TILE_SIZE

STATUS_BAR_ROW = 0
TOP_WALL_ROW = 1
PLAYAREA_START_ROW = 2
PLAYAREA_END_ROW = 21
BOTTOM_WALL_ROW = 22
TRANSIENT_INFO_ROW = 23

PLAYAREA_WIDTH = 32
PLAYAREA_HEIGHT = 20
PLAYABLE_WIDTH = 30
PLAYABLE_HEIGHT = 20
PLAYABLE_AREA = PLAYABLE_WIDTH * PLAYABLE_HEIGHT

ENTRY_DOOR_COLS = (15, 16)
EXIT_DOOR_COLS = (15, 16)
ENTRY_DOOR_ROW = BOTTOM_WALL_ROW
EXIT_DOOR_ROW = TOP_WALL_ROW

START_POSITION_ROW = 21

MINE_BASE_DENSITY = 0.10
MINE_DENSITY_INCREASE_PER_LEVEL = 0.05
MINE_DENSITY_MAX_MULTIPLIER = 2.0

BUFFER_ZONE_RADIUS = 1

INITIAL_LIVES = 3

BASE_SCORE_PER_LEVEL = 100
DEATH_PENALTY = 50
EFFICIENCY_BONUS_MAX = 1.5

REPLAY_SPEED_MULTIPLIER = 10.0
REPLAY_AUTO_ADVANCE_TIMEOUT = 2.0

COLOR_BLACK = 0
COLOR_DARK_BLUE = 1
COLOR_DARK_PURPLE = 2
COLOR_DARK_GREEN = 3
COLOR_BROWN = 4
COLOR_DARK_GRAY = 5
COLOR_LIGHT_GRAY = 6
COLOR_WHITE = 7
COLOR_RED = 8
COLOR_ORANGE = 9
COLOR_YELLOW = 10
COLOR_GREEN = 11
COLOR_CYAN = 12
COLOR_LIGHT_BLUE = 13
COLOR_LAVENDER = 14
COLOR_PINK = 15

WALL_COLOR = COLOR_LIGHT_GRAY
PLAYER_COLOR = COLOR_WHITE
MINE_COLOR = COLOR_BLACK
